# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push]

jobs:    
  build:

    env:
      AWS_DEFAULT_REGION: us-west-2

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade flake8 pytest tox black converge wheel twine
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build
      run: |
        tox
        python setup.py bdist_wheel --universal
        python setup.py sdist